redis:
  image: redis:6-buster
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
    - ./redis:/usr/local/etc/redis
    - ./db/redis:/data
    - ./db/redis:/etc
  ports:
    - 6379:6379
  user: "${UID}:${GID}"
