// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Etherlands

import "strconv"

type AccessFlag byte

const (
	AccessFlagNone     AccessFlag = 0
	AccessFlagBuild    AccessFlag = 1
	AccessFlagDestroy  AccessFlag = 2
	AccessFlagInteract AccessFlag = 3
	AccessFlagSwitch   AccessFlag = 4
)

var EnumNamesAccessFlag = map[AccessFlag]string{
	AccessFlagNone:     "None",
	AccessFlagBuild:    "Build",
	AccessFlagDestroy:  "Destroy",
	AccessFlagInteract: "Interact",
	AccessFlagSwitch:   "Switch",
}

var EnumValuesAccessFlag = map[string]AccessFlag{
	"None":     AccessFlagNone,
	"Build":    AccessFlagBuild,
	"Destroy":  AccessFlagDestroy,
	"Interact": AccessFlagInteract,
	"Switch":   AccessFlagSwitch,
}

func (v AccessFlag) String() string {
	if s, ok := EnumNamesAccessFlag[v]; ok {
		return s
	}
	return "AccessFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
