// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Etherlands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DistrictTeamPermissionMap struct {
	_tab flatbuffers.Table
}

func GetRootAsDistrictTeamPermissionMap(buf []byte, offset flatbuffers.UOffsetT) *DistrictTeamPermissionMap {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DistrictTeamPermissionMap{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DistrictTeamPermissionMap) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DistrictTeamPermissionMap) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DistrictTeamPermissionMap) Permissions(obj *TeamPermissionMap, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DistrictTeamPermissionMap) PermissionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DistrictTeamPermissionMap) Districts(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *DistrictTeamPermissionMap) DistrictsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DistrictTeamPermissionMap) MutateDistricts(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func DistrictTeamPermissionMapStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DistrictTeamPermissionMapAddPermissions(builder *flatbuffers.Builder, permissions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(permissions), 0)
}
func DistrictTeamPermissionMapStartPermissionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DistrictTeamPermissionMapAddDistricts(builder *flatbuffers.Builder, districts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(districts), 0)
}
func DistrictTeamPermissionMapStartDistrictsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func DistrictTeamPermissionMapEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
