// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Etherlands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GroupPermission struct {
	_tab flatbuffers.Table
}

func GetRootAsGroupPermission(buf []byte, offset flatbuffers.UOffsetT) *GroupPermission {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GroupPermission{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GroupPermission) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GroupPermission) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GroupPermission) Group() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GroupPermission) Flag() AccessFlag {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return AccessFlag(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GroupPermission) MutateFlag(n AccessFlag) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *GroupPermission) Value() FlagValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return FlagValue(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GroupPermission) MutateValue(n FlagValue) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func GroupPermissionStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GroupPermissionAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func GroupPermissionAddFlag(builder *flatbuffers.Builder, flag AccessFlag) {
	builder.PrependByteSlot(1, byte(flag), 0)
}
func GroupPermissionAddValue(builder *flatbuffers.Builder, value FlagValue) {
	builder.PrependByteSlot(2, byte(value), 0)
}
func GroupPermissionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
