// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Etherlands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GroupPermissionMap struct {
	_tab flatbuffers.Table
}

func GetRootAsGroupPermissionMap(buf []byte, offset flatbuffers.UOffsetT) *GroupPermissionMap {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GroupPermissionMap{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GroupPermissionMap) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GroupPermissionMap) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GroupPermissionMap) Permissions(obj *GroupPermission, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GroupPermissionMap) PermissionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GroupPermissionMapStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GroupPermissionMapAddPermissions(builder *flatbuffers.Builder, permissions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(permissions), 0)
}
func GroupPermissionMapStartPermissionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GroupPermissionMapEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
