// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Etherlands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TeamPermissionMap struct {
	_tab flatbuffers.Table
}

func GetRootAsTeamPermissionMap(buf []byte, offset flatbuffers.UOffsetT) *TeamPermissionMap {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TeamPermissionMap{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TeamPermissionMap) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TeamPermissionMap) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TeamPermissionMap) Permissions(obj *TeamPermission, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TeamPermissionMap) PermissionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TeamPermissionMapStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TeamPermissionMapAddPermissions(builder *flatbuffers.Builder, permissions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(permissions), 0)
}
func TeamPermissionMapStartPermissionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TeamPermissionMapEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
